import Head from 'next/head';
import { signIn } from 'next-auth/react';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="">
          This is a public page. You can see it without being authenticated.
        </h1>
        <button className="" onClick={() => signIn()}>Sign In</button>
      </main>
    </>
  )
}
